services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: tasks_db
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
    volumes:
      - ./app:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tasks_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: